//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsClient.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.EnumUserDocumentType DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeighborhoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.EnumUserTitle TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.EnumUserType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressNumber {
            get {
                return this.AddressNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressNumberField, value) != true)) {
                    this.AddressNumberField = value;
                    this.RaisePropertyChanged("AddressNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.EnumUserDocumentType DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Neighborhood {
            get {
                return this.NeighborhoodField;
            }
            set {
                if ((object.ReferenceEquals(this.NeighborhoodField, value) != true)) {
                    this.NeighborhoodField = value;
                    this.RaisePropertyChanged("Neighborhood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nif {
            get {
                return this.NifField;
            }
            set {
                if ((object.ReferenceEquals(this.NifField, value) != true)) {
                    this.NifField = value;
                    this.RaisePropertyChanged("Nif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.EnumUserTitle Title {
            get {
                return this.TitleField;
            }
            set {
                if ((this.TitleField.Equals(value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.EnumUserType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumUserDocumentType", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    public enum EnumUserDocumentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefinied = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BI = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CC = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumUserTitle", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    public enum EnumUserTitle : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefinied = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Eng = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sr = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sra = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumUserType", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    public enum EnumUserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefinied = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Particular = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Company = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operation", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class Operation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.EnumOperationType OperationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtOperation {
            get {
                return this.DtOperationField;
            }
            set {
                if ((this.DtOperationField.Equals(value) != true)) {
                    this.DtOperationField = value;
                    this.RaisePropertyChanged("DtOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.EnumOperationType OperationType {
            get {
                return this.OperationTypeField;
            }
            set {
                if ((this.OperationTypeField.Equals(value) != true)) {
                    this.OperationTypeField = value;
                    this.RaisePropertyChanged("OperationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumOperationType", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    public enum EnumOperationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Auto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Travel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Infomration = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Policy", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebFormsClient.ServiceReference2.PolicyDetail))]
    public partial class Policy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.EnumPolicyState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.EnumPolicyType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.EnumPolicyState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.EnumPolicyType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyDetail", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyDetail : WebFormsClient.ServiceReference2.Policy {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.PolicyConditions ConditionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.PolicyGeneralData GeneralDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.PolicyDocument[] ListDocumentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.PolicyConditions Conditions {
            get {
                return this.ConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionsField, value) != true)) {
                    this.ConditionsField = value;
                    this.RaisePropertyChanged("Conditions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.PolicyGeneralData GeneralData {
            get {
                return this.GeneralDataField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralDataField, value) != true)) {
                    this.GeneralDataField = value;
                    this.RaisePropertyChanged("GeneralData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.PolicyDocument[] ListDocuments {
            get {
                return this.ListDocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ListDocumentsField, value) != true)) {
                    this.ListDocumentsField = value;
                    this.RaisePropertyChanged("ListDocuments");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumPolicyState", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    public enum EnumPolicyState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Simulated = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitPayment = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumPolicyType", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    public enum EnumPolicyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotDefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Auto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Travel = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyConditions", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyConditions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.PolicyBonus[] ListPolicyBonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.PolicyCoverage[] ListPolicyCoverageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.PolicyBonus[] ListPolicyBonus {
            get {
                return this.ListPolicyBonusField;
            }
            set {
                if ((object.ReferenceEquals(this.ListPolicyBonusField, value) != true)) {
                    this.ListPolicyBonusField = value;
                    this.RaisePropertyChanged("ListPolicyBonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.PolicyCoverage[] ListPolicyCoverage {
            get {
                return this.ListPolicyCoverageField;
            }
            set {
                if ((object.ReferenceEquals(this.ListPolicyCoverageField, value) != true)) {
                    this.ListPolicyCoverageField = value;
                    this.RaisePropertyChanged("ListPolicyCoverage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyGeneralData", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyGeneralData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BonusInsuranceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConcurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FragmentationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntermediateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebFormsClient.ServiceReference2.PolicyVehicle[] ListVehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalRiskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalInsuranceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BonusInsurance {
            get {
                return this.BonusInsuranceField;
            }
            set {
                if ((this.BonusInsuranceField.Equals(value) != true)) {
                    this.BonusInsuranceField = value;
                    this.RaisePropertyChanged("BonusInsurance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessUnit {
            get {
                return this.BusinessUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessUnitField, value) != true)) {
                    this.BusinessUnitField = value;
                    this.RaisePropertyChanged("BusinessUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientNumber {
            get {
                return this.ClientNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNumberField, value) != true)) {
                    this.ClientNumberField = value;
                    this.RaisePropertyChanged("ClientNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Concurrency {
            get {
                return this.ConcurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrencyField, value) != true)) {
                    this.ConcurrencyField = value;
                    this.RaisePropertyChanged("Concurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fragmentation {
            get {
                return this.FragmentationField;
            }
            set {
                if ((object.ReferenceEquals(this.FragmentationField, value) != true)) {
                    this.FragmentationField = value;
                    this.RaisePropertyChanged("Fragmentation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InitDate {
            get {
                return this.InitDateField;
            }
            set {
                if ((this.InitDateField.Equals(value) != true)) {
                    this.InitDateField = value;
                    this.RaisePropertyChanged("InitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Intermediate {
            get {
                return this.IntermediateField;
            }
            set {
                if ((object.ReferenceEquals(this.IntermediateField, value) != true)) {
                    this.IntermediateField = value;
                    this.RaisePropertyChanged("Intermediate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebFormsClient.ServiceReference2.PolicyVehicle[] ListVehicles {
            get {
                return this.ListVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListVehiclesField, value) != true)) {
                    this.ListVehiclesField = value;
                    this.RaisePropertyChanged("ListVehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalRisk {
            get {
                return this.LocalRiskField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalRiskField, value) != true)) {
                    this.LocalRiskField = value;
                    this.RaisePropertyChanged("LocalRisk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMode {
            get {
                return this.PaymentModeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentModeField, value) != true)) {
                    this.PaymentModeField = value;
                    this.RaisePropertyChanged("PaymentMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalInsurance {
            get {
                return this.TotalInsuranceField;
            }
            set {
                if ((this.TotalInsuranceField.Equals(value) != true)) {
                    this.TotalInsuranceField = value;
                    this.RaisePropertyChanged("TotalInsurance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyDocument", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyBonus", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyBonus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberYearsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((this.BonusField.Equals(value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberYears {
            get {
                return this.NumberYearsField;
            }
            set {
                if ((this.NumberYearsField.Equals(value) != true)) {
                    this.NumberYearsField = value;
                    this.RaisePropertyChanged("NumberYears");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyCoverage", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyCoverage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoverageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InsuredValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoverageType {
            get {
                return this.CoverageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CoverageTypeField, value) != true)) {
                    this.CoverageTypeField = value;
                    this.RaisePropertyChanged("CoverageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InsuredValue {
            get {
                return this.InsuredValueField;
            }
            set {
                if ((this.InsuredValueField.Equals(value) != true)) {
                    this.InsuredValueField = value;
                    this.RaisePropertyChanged("InsuredValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyVehicle", Namespace="http://schemas.datacontract.org/2004/07/WSAcademiaSeguros.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyVehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint NSeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CC {
            get {
                return this.CCField;
            }
            set {
                if ((this.CCField.Equals(value) != true)) {
                    this.CCField = value;
                    this.RaisePropertyChanged("CC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint NSeat {
            get {
                return this.NSeatField;
            }
            set {
                if ((this.NSeatField.Equals(value) != true)) {
                    this.NSeatField = value;
                    this.RaisePropertyChanged("NSeat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationField, value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IAcademia")]
    public interface IAcademia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/IsOnline", ReplyAction="http://tempuri.org/IAcademia/IsOnlineResponse")]
        bool IsOnline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/IsOnline", ReplyAction="http://tempuri.org/IAcademia/IsOnlineResponse")]
        System.Threading.Tasks.Task<bool> IsOnlineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/LogIn", ReplyAction="http://tempuri.org/IAcademia/LogInResponse")]
        bool LogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/LogIn", ReplyAction="http://tempuri.org/IAcademia/LogInResponse")]
        System.Threading.Tasks.Task<bool> LogInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetUserData", ReplyAction="http://tempuri.org/IAcademia/GetUserDataResponse")]
        WebFormsClient.ServiceReference2.User GetUserData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetUserData", ReplyAction="http://tempuri.org/IAcademia/GetUserDataResponse")]
        System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.User> GetUserDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetLastOperation", ReplyAction="http://tempuri.org/IAcademia/GetLastOperationResponse")]
        WebFormsClient.ServiceReference2.Operation[] GetLastOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetLastOperation", ReplyAction="http://tempuri.org/IAcademia/GetLastOperationResponse")]
        System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.Operation[]> GetLastOperationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetUserPolicies", ReplyAction="http://tempuri.org/IAcademia/GetUserPoliciesResponse")]
        WebFormsClient.ServiceReference2.Policy[] GetUserPolicies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetUserPolicies", ReplyAction="http://tempuri.org/IAcademia/GetUserPoliciesResponse")]
        System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.Policy[]> GetUserPoliciesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetPolicyDetail", ReplyAction="http://tempuri.org/IAcademia/GetPolicyDetailResponse")]
        WebFormsClient.ServiceReference2.PolicyDetail GetPolicyDetail(string policyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetPolicyDetail", ReplyAction="http://tempuri.org/IAcademia/GetPolicyDetailResponse")]
        System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.PolicyDetail> GetPolicyDetailAsync(string policyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetDocumentContent", ReplyAction="http://tempuri.org/IAcademia/GetDocumentContentResponse")]
        string GetDocumentContent(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/GetDocumentContent", ReplyAction="http://tempuri.org/IAcademia/GetDocumentContentResponse")]
        System.Threading.Tasks.Task<string> GetDocumentContentAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/SaveNewFoto", ReplyAction="http://tempuri.org/IAcademia/SaveNewFotoResponse")]
        bool SaveNewFoto(string photo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcademia/SaveNewFoto", ReplyAction="http://tempuri.org/IAcademia/SaveNewFotoResponse")]
        System.Threading.Tasks.Task<bool> SaveNewFotoAsync(string photo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAcademiaChannel : WebFormsClient.ServiceReference2.IAcademia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcademiaClient : System.ServiceModel.ClientBase<WebFormsClient.ServiceReference2.IAcademia>, WebFormsClient.ServiceReference2.IAcademia {
        
        public AcademiaClient() {
        }
        
        public AcademiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcademiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcademiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcademiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsOnline() {
            return base.Channel.IsOnline();
        }
        
        public System.Threading.Tasks.Task<bool> IsOnlineAsync() {
            return base.Channel.IsOnlineAsync();
        }
        
        public bool LogIn(string username, string password) {
            return base.Channel.LogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LogInAsync(string username, string password) {
            return base.Channel.LogInAsync(username, password);
        }
        
        public WebFormsClient.ServiceReference2.User GetUserData() {
            return base.Channel.GetUserData();
        }
        
        public System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.User> GetUserDataAsync() {
            return base.Channel.GetUserDataAsync();
        }
        
        public WebFormsClient.ServiceReference2.Operation[] GetLastOperation() {
            return base.Channel.GetLastOperation();
        }
        
        public System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.Operation[]> GetLastOperationAsync() {
            return base.Channel.GetLastOperationAsync();
        }
        
        public WebFormsClient.ServiceReference2.Policy[] GetUserPolicies() {
            return base.Channel.GetUserPolicies();
        }
        
        public System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.Policy[]> GetUserPoliciesAsync() {
            return base.Channel.GetUserPoliciesAsync();
        }
        
        public WebFormsClient.ServiceReference2.PolicyDetail GetPolicyDetail(string policyNumber) {
            return base.Channel.GetPolicyDetail(policyNumber);
        }
        
        public System.Threading.Tasks.Task<WebFormsClient.ServiceReference2.PolicyDetail> GetPolicyDetailAsync(string policyNumber) {
            return base.Channel.GetPolicyDetailAsync(policyNumber);
        }
        
        public string GetDocumentContent(int ID) {
            return base.Channel.GetDocumentContent(ID);
        }
        
        public System.Threading.Tasks.Task<string> GetDocumentContentAsync(int ID) {
            return base.Channel.GetDocumentContentAsync(ID);
        }
        
        public bool SaveNewFoto(string photo) {
            return base.Channel.SaveNewFoto(photo);
        }
        
        public System.Threading.Tasks.Task<bool> SaveNewFotoAsync(string photo) {
            return base.Channel.SaveNewFotoAsync(photo);
        }
    }
}
